'use strict';

import PropTypes from "prop-types";

import Head from "next/head";
import Nav from "../components/Nav/Nav";

const MasterLayout = ({title, pageName, children}) => {

    //UI
    return (
        <div className={`${pageName}-page`}>

            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Nav/>

            <main>

                <div className="container">
                    <div className="row">
                        <div className="col-12">
                            {children}
                        </div>
                    </div>
                </div>
            </main>

        </div>
    )
}

MasterLayout.defaultProps = {
    title: '',
    pageName: '',
}

MasterLayout.propTypes = {
    title: PropTypes.string.isRequired,
    pageName: PropTypes.string.isRequired,
    children: PropTypes.node,
}

export default MasterLayout